sudo: required
language: java
jdk: oraclejdk8
services:
- docker

env:
  global:
  - secure: jYU9u6bJtmwZTp5FxP329S3Jz88JHd25DpCUnMBp7S4QIK7o78xlWGYp6TdrTVJiuDCfI6cPCaVWBZAVunW0mnzVwJ88oUKySULzy9/C8+slVgSLiSj2s/fm0uDg/UR5v1RaE1yGZCK7RqsghJGaY3/taKHWyLCRB2ltKEGhHOLU+d74Aw0F8Dkn3RlZkdhbeCO9buSe01jI5qyROKW993etKWGJXNhx7nR3Daz+qwo7RNCCs+GIIzJsHkwZ9WOju/sJQm3txileWq/9s8V+udSB+u14o7DHsvAgq75wsNw9cvveP2G3eXFiP5O6IIhNmAJHhdL70sUuYi4NKMf7aZlcBU6GvAXPmMmzCxx/O1Lit8NBY9hZ7hNwyWHelM8YC5YEA4zJxJmfknz5nVqOEPahvGP8t2c/0DlmlTACe5tuiIghAQi5LM6o3oBAMYpex67NP+vl1jqKTlTk05d1mnTU5FgQQrGMXuf2aLYpou9o1DyI7hgUMZwYekXyAD9DP2U54yIGW21y1xzmkh0LBDaYSzg6UeIZiYuOxxkC/9YuVIFLrz68+t+EH2HD1f5/A8NAl7dlN8II24SDDJwhbsV0KTNr67+0OgV+h0ZlSVpiNJhGRKORGLmH791xl7FFRu/fEnbaSOGQg9G2v+C5MHqpmnVfuFPiYVKlPTtrcss=
  - secure: qoiKtyHTFYhHJ9Lk3OGe8yiSgDdjO2RdHdxXoFJ2Wp5MPEKrHTV8e7FdTezPj0xEpPu5NkL/VlQbu5c/XKYthyJfHOFkL7VUJLrpOllHCWsGQ81zpZiDM+aKMWI+z+sNrbSdXCGLbAzAShl0iF7Iajd7gjJQaZaJx9HXNnnI6aiotDN657Mez/X3K9sCPQie1vPiTUjqnQNOpl5KVVDq34RMUPka9I9X/idmYhJqFd/57e7mbylD5PsOGBgKgpqUydSfKNECvogWtNPJO53sAHFYj442oZknmlKW1latk3ybwaqsZdqZPv35j+YX4GKKE9ult87nQ0YpjaIJh0YU2A1pWULstZGFg8h0/ca2p2CfIBMkNDLATiygTmEIqTq7z4rUy2MLfPKsAGHhxC2FWk/FuoTeGcT61xA3NXyULBH0CdnVP+VPUFyBkvF/GcU5LLTn46XVuzNTFumK+9m45Vu79G8UVGQT8ncQhvQhPUj3xK+B6HFVT31TwXvVWSehpTeEfHlDxrN+bEq/x/X64G4cEG4o6zAHvh7dpEzZtri+aqpI5t3q4fj4+4djr0+oWSuxa5qdOdfOVFDWgLQpSWb7X+B1cL+klifmEZyQgcq6VsH0BtgwRRrbpuRlKhZ3PTnwQpxZW6ZrPGSoEmwKJKXQVA3cEQCNvBo/3fpPze4=
  - secure: vO5EPkmThvnq1J8pyzu093mTiyH+1OGR9lalYz+1YaTDt08HrdhiUAFn3929CMrz5ENAbZnNJ8GPt/8+ot9WmaeJI+Kk62Md5Fdm3NU9EV0CTFvIjbx2pcI/h55Ha/HEHvk5Dzg2d1TK9csB3uSfand34GJMLzdeGsK4QynFmfTC8gKVZ5jBNYmnUUKrojZMxnmqrbpHYeM3al/TfL2EDx7xVPLKsCKu57hjhwmrFJUg/GZxM8k4sO3lt3ZaUoUEuK2B7/oVdIa9gVe6Y5QsJ/grXe418yHH5tcgVuieJd9vIMHNwwg4eg2Io6GReXMejtipp4PoiFHUt9rj4uUx97HzuZgnYXtoLC6EJ6OLTAdPpjql37zw4uB6VIAemeZOOxZDoL/vqDtNpaO0I9AUmfV6m4qLs43MRRlUeqb+NBRrQsIEYqh6MybBek7Olat2Bl2bkVBNOoYSeTo0KFxL79aCYAGv3NHNOmF8Py3UV6WT+Uu7haFJQIKt0rXuswKxBceVGVRCToFmKRs9e3/846/W+WA7wgn3vW6x3E3aS1JAiV3VNsyoqeuhTzHFDdwfSy5o3rS6pURdw4KKusAmX5zS2ovCgQYIO1MgIfjFNYui1/t1dBVNeI2fRQHL9VogZ6yGrHZw6iGXYBb+o7oLFMKs5GqGgVb8XcR1IJO5Skk=
  - secure: l4ZGCyT38b3q6DezZVHWuWE0gzz/MJB6zWMXmVclRlrp991SdwhFXfNb3BoSfw7CYg2sZhyeBAJhIZhTSj5FCiGGTaDG8rn8IYkzrZzB5eBK7jRCWDSyjMJ6AkAAkSdR+BQySugA4tle5Z5QVfizap5HTTD5jv3fAU+6lawEVn+MKYVPJ9CsDxlNh/PvXUT7b4rGBQKvxhhECqi84cACYzU7z8lW5X3jjGfDN/0r4oynq9JmYCyyBiSyk1ysPG3ryLdQMPIPmhDwPWU1PB+wFHeZmR1dlWMc4Gt7rOAtS/gnhJRShTKPbiKyjZ4FSlcR0i4Aam2T7aB0PiVG7mdt+YurEUoLtqXNckBkvlIvc6Gd2erlH/CUPK1b7PSyA4fyQUHaFyYGnC2E9rfzRZ1uJ+TntnwqTuTOUZqi6L9saENPXO+yNRdIkhAkaYG/Yml2mlaTp2/8CqRJTHEGOVhHe4mCKJHf0xI3GeL0davCRYRwdG0iH+YEFhVhsySlfj4By9xi4RW4hYy0BFzBErW4a8reNM28WxjZwXhpTOAFKKkk5V0wlY2+rqfzmRfR+Ph7lL5dnQC3tiVujeDUAKbDo+yrMxRDVygEGGgf348F/4Lo7ZyasmffA4qsoXh1spyZ9GYcUdPUedFIjdrc5X0TpNT2UjSolqEqbok7e9qnaX4=
  - secure: g4rOxogNlbszFMMCIa0GfdW1Brfky/q9UllfahEJ4hwDqpo1u+0f3tGLX8fq4E2rBQgtPKTglKfdfBsxfKZicXYlYN5NiQTLU3eypBJrttoIqABjQkc+Jqc1B7BJGoSXN9ywliy/uueVdnPzVRwlyiBFCPmoSQrAS8bgY2fajmpCDSBjulJVe9H+aq6H1SquhZ69n9wSr1JbZYCSoir4U9i2juCBWb+cftP8cYoT4Xm4+cepiFCvH7r+AAMX0iMWPydOaeJTPohyxccpkYjdAV3WvlHSD0/dSZhKp20lyGrLJldQlcwGFWK6qx4TYiOM3Y2lEC8yWtJujIcENQ/z8eBVxYIZWKMjm4zFcfnZjx16e1EiWo0/OwwTAoVg96BzqSn2LyLr/EJxjet1uLDfSxcFlsjUwXY4rNNzCC7cXk32EjTlIV4Zdh7LJ9PLMK7/sRuGTcJAR/O4ZooY+rkYr6+8TA9RBzFuEh6EvUCMNmM6GR6sWxechOVeyxQMI9a3ygdVa89LcBkW5G3jLfEyFBzE/RUjQjBtW21uVtcIhPdRpdH2a5+ssbxyShOe6+crut1K9nVrB4xlr2v4qQYY8XWBSh+82tPV9Zn+4r+KtvgkVYR7THwo0gKYCwtTHuMy8lIbc0BG6UlC5V4UUTdAV+roBQC1En8Jyms9996sIAM=
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: rawsanj
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
- bash <(curl -s https://codecov.io/bash)
