management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

---
spring:
  profiles:
    active: cloud
  datasource:
    url: ${vcap.services.broker-db.credentials.jdbcurl:jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE}
    username: ${vcap.services.broker-db.credentials.username:sa}
    password: ${vcap.services.broker-db.credentials.password:}


AWS_DEFAULT_REGION: us-east-1

AWS_S3_ADMIN_USER: s3-admin


# Open the Database Ports in default Security Group